### ISSUE TITLE
大佬您好请教关于项目温度的问题

### ISSUE THREAD

**Issue by SoraKasvgano** [liuyuansharp/RouterMonitor#2]
不知可否请教一下：

在使用作者原项目的时候，温度显示总显示 95-107，应该是核心温度。

后面看了关于从netdata获取sensor key的说明，但是我发现最新版本的netdata 无论是v0 v1 v2界面 都不会直接显示key，不知怎么设置通过什么渠道可以获取图表的正确的温度key呢。。。

`sensors.temp_thermal_zone0_hwmon_hwmon0`
`sensors.temp_thermal_zone0_thermal_thermal_zone0`

好像都不行

**Comment by liuyuansharp** [comment]
点Sensors，然后
![image](https://github.com/liuyuansharp/RouterMonitor/assets/30963599/19a2bad7-7179-4121-866d-0bb162b595aa)

**Comment by SoraKasvgano** [comment]
> 点Sensors，然后 ![image](https://user-images.githubusercontent.com/30963599/283119578-19a2bad7-7179-4121-866d-0bb162b595aa.png)

老哥问了一下官方，原来是新版本netdata开发过程中把ID标签移除了，他们昨天刚修复了这个问题，谢谢老哥
另外也可以通过这里查询到 :19999/api/v1/charts
